import '../js/game_manager.js';
import '../js/animframe_polyfill.js';
import '../js/keyboard_input_manager.js';
import '../js/html_actuator.js';
import '../js/grid.js';
import '../js/tile.js';
import '../js/local_score_manager.js';
import '../js/application.js';
import '../style/main.css';
